# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
